project:
  type: website
  output-dir: docs

website:
  title: "Pesquisa Meros SC"
  navbar:
    logo: meroiconwhite.png
    left:
      - text: "Equipe"
        href: index.qmd

      - text: "Stero-BRUV"
        menu:
          - text: "Protocolo de Campo"
            href: bruv.qmd
          - text: "Guia Rápido | Calibração"
            href: quick-cal.qmd
          - text: "Manual SeaGIS | Calibração"
            href: seagis-cal.qmd
          - text: "EventMeasure"
            href: eventmeasure.qmd

      - text: "Mergulho Científico"
        menu:
          - text: "Nossas Diretrizes"
            href: sci-dive.qmd
          - text: "Plano de Emergência"
            href: emergence.qmd

      - text: "Pesquisa"
        href: https://guidogrimaldi.shinyapps.io/PesquisaMerosSC/

    right:
      - icon: envelope
        href: mailto:pesquisasc@merosdobrasil.org
      - icon: globe
        href: https://merosdobrasil.org/

  back-to-top-navigation: true

  page-footer:
    left:
      - text: "Created by Guido Grimaldi, PhD."
        href: https://github.com/GuidoGrimaldi
    center: "© 2026 Projeto Meros do Brasil."

format:
  html:
    theme:
      - cerulean
      - brand
    css: styles.css
    respect-user-color-scheme: true
  pdf:
    documentclass: scrreprt

editor: visual
