---
title: "Projeto Meros do Brasil"
subtitle: "BRUV: Guia rápido de campo."
author: 
  name: Pesquisa Meros SC
  email: pesquisasc@merosdobrasil.org
  affiliation: 
    name: Instituto Meros do Brasil
    url: https://merosdobrasil.org/
abstract: "Este protocolo está em contínuo aprimoramento. É sempre recomendável relê-lo para se manter atualizado sobre as mudanças."

abstract-title: "About"

# Formato
format:
  html:
    toc-title: "Conteúdo"
    toc: true
    toc-location: right
    toc-expand: true
    toc-depth: 1
    number-sections: true

# Fonte ---------------------------
fontfamily: baskervald
fontsize: 12pt

# Opções de execução --------------
execute: 
  warning: false
  freeze: auto

# Layout da página ----------------
geometry: 
  - margin = 1in
---

# Procedimentos Pré-Campo

-   Verificar carga das baterias.

-   Verificar armazenamento dos cartões de memória.

-   Verificar funcionamento das câmeras.

-   Verificar preseça de todos os componentes e peças do *BRUV*.

-   Verificar presença de todas as porcas para ajuste das .

# Procedimentos de Campo

## Preparação para o lançamento

-   Monte os pés do BRUV.

-   Prepare a haste da isca com o cano de armazenamento.

-   ::: {.callout-tip appearance="simple"}
    **Não adicione a isca ainda, para não ficar pingando no barco. Deixe para pôr no último momento.**
    :::

-   Libere o cabo vermelho em comformidade com a profudidade local estimada. Ex: para 15m de profundidade, libere 17 braças ( 1 braça \~1.5m).

-   Amare a **ponta solta** do cabo de lançamento (**corda vermelha**) na argola da bóia de meia água do BRUV.

-   Amarre a bóia de sinalização de superfície (**bóia laranja**) ao cabo de lançamento.

-   ::: {.callout-caution appearance="minimal"}
    NÃO passe o cabo SOMENTE no D-ring plástico da bóia de sinalização, Passe também por dentro do tirante horizontal da bóia como backup de segurança para caso do D-ring quebre.
    :::

-   Retire ambas as câmeras e ligue-as (**Pressione o botão lateral**).

-   Conecte a câmera ao celular **via bluetooth** (Ver Quick GoPro App.)

-   **Formate os cartões de memória**.

-   Ponha para gravar.

-   Verifique se de fato está gravando.

-   ::: callout-tip
    Veja o monitor. Quando está gravando, a GoPro emite um luz vermelha intermitente.
    :::

-   Devolva as câmaras aos seus RESPECTIVOS cases.

-   **Cuidado para não por de cabeça para baixo!**

-   ::: {.callout-tip appearance="simple"}
    Se atente as marcações no bruv, elas devem coincidir. Lembre-se **vermelho** é bombordo (esquerda) e **verde** é boreste (direita).
    :::

-   Adicione a isca ao cano e acople a haste da isca no BRUV.

-   ::: callout-caution
    Quando for conectar a haste da isca, tenha cuidado com a bóia de meia água do BRUV. Está deve passar por fora da haste. Lembre-se de levantá-la antes de fixar a haste.
    :::

-   VERIFIQUE SE O PROFUDIMETRO ESTA MARCANDO 0m. Caso não esteja, retorne o ponteiro a marcação inicial.

## Lançamento na água

-   Tudo pronto! Vamos lançar pra água!

-   Precisa de pelo menos duas pessoas, uma para lançar e outra para safar o cabo. Bom mesmo é três, porque fica um atento as anotações e coleta do ponto no GPS (protocolo a criar)

-   Apoie o BRUV no bordo, metade das pernas dentro, metade fora, com a isca virada para o mar.

    ::: {.callout-warning appearance="simple"}
    Não solte na popa, ao menos que o motor da embarcação esteja desligado, pois corre risco de enroscar no hélice.
    :::

-   Em caso de embarcação em movimento, solte o mais vertical e rápido possível, evitando assim muita derivação.

-   Solte-o e a medida que ganha profundidade realiza alguns puxões para ganhar prumo.

-   Se puxar demais ou entrar na água em uma posição ruim, o sistema bruv ficara de ponta cabeçã ou tompará para frente.

-   Já aconteceu de o sistema cair em pé, mas de alguma maneira tobar para trás apos muitos minutos em posição correta. Acredito que tenha sido o cabo curto demais em relação a ondulação da maré, mas é preciso verificar mais.

-   Quando sentir que a sonda chegou ao fundo, lançe o cabo restante, com a bóia de sinalização.

    ::: {.callout-caution appearance="simple"}
    Não esqueça de marcar o ponto no GPS! É para cada lançamento!
    :::

## Que informações anotar?

::: {.callout-important appearance="simple"}
Leve sua prancheta ou caderneta de campo!
:::

-   Data

-   Local

-   Participantes

-   Hora de lançamento

-   Hora de retirada

-   Ponto GPS

-   Profundidade

-   ID do BRUV (B1, B2 ou B3)

## Remoção da água

-   Enquanto um dos integrantes puxa o sistema BRUV da água, o outro deve ir recolhendo a corda do convez.

-   Uma vez embarcado o equipamento:

    -   Anote a hora de retirada;

    -   Retire a bóia de sinalização;

    -   Solte e recolha o cabo;

    -   Registre a profundidade e retorne o ponteiro do profundímetro para a marcação de zero;

    -   Retire a haste que sustenta o cano da isca e dispense o material na água;

    -   Passe uma água no cano da isca para retirar o excesso de peixe morto;

    -   Caso não vá mais utilizar os BRUVs, desmonte e guarde-os nas bolsas de transporte;

    -   Caso ainda vá utilizar, deixe-os montados, sem a haste da isca e de forma organizada, em algum local do convez de modo a permitir a circulação da tripulação.

::: {.callout-caution appearance="simple"}
Ao guardar os BRUVs na bolsa de transporte, tenha especial cuidado com as lentes, de modo a evitar arranhões, pois estes interferem na análise das imagens.
:::

# Pós-Campo

## Lavagem

-   Lave toda a estrutura dos bruvs com água doce.

-   Faça com que a água entre nos tubos dos pés.

## Cartões de memória & Baterias

-   Retire a bateria da câmera, isso facilita o acesso ao cartão de memória.

-   Retire o cartão de memória da câmera.

-   **Copie** todos os arquivos do cartão para o **drive externo** do Meros SC (Ver Transferindo arquivos ao HD.

::: callout-tip
**Faça o quanto antes! Não deixe para fazer depois, pois terá dificuldade de se lembrar dos metadados de campo.**
:::

-   **NÃO formate os cartões pelo computador.** Isso deve ser feito via celular (Ver: Quick GoPro App).

-   Devolva os cartões as suas respectivas câmeras (Ver Foto).

    ::: callout-tip
    A dica é fazer este processo individualmente para cada BRUV. Escolha um dos lados para começar (E/D), depois realize cada etapa desta seção na câmera escolhida e só após concluido o passo-a-passo, siga para o outro lado. Assim você não irá se perder e cometer erros no trato das informações.
    :::

-   Guarde a bateria no case de campo no compartimento "A carregar".

    ::: {.callout-tip appearance="simple"}
    **Facilite. Deixe as baterias já carregadas e prontas para o próximo campo.**
    :::
